dataset: 'cifar10'
model_size: 'xxs'
training: True
test: True
unpruned_save_path: './saved_models/unpruned_weights.pth'
train_allocation: 0.8
epoch: 2
batch_size: 128
learning_rate: 0.001
momentum: 0.9